leftnav:
- identifier: c25c7dc7-8135-212d-2e51-d71926d5ca0d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 65cda45b-5a78-a343-564a-7a5fe9a9bb36
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 95059208-660f-67c2-1d58-b34ec5442c78
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 0f3d66c0-7208-8711-54e4-3dd52afe546e
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 3acd4ea7-f5dc-f68e-a462-a03645b0c2d5
  name: Projects
  pageRef: /pages/projects
  weight: 50
